# Number of labels to fetch (optional). Defaults to 100
numLabels: '40'
# These labels will not be used even if the issue contains them (optional).
# Pass a blank array if no labels are to be excluded.
# excludeLabels: []
excludeLabels:
  - pinned
# custom configuration to override default behaviour
# control explicitly what gets added and when
# custom:
#   - location: title
#     keywords:
#       - enable
#     labels:
#       - enhancement
#   - location: title
#     keywords:
#       - fix
#     labels:
#       - bug
#   - location: title
#     keywords:
#       - doc
#     labels:
#       - documentation
