version: 2
mergeable:
  - when: pull_request.*
    name: 'Ingore WIP'
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
  - when: pull_request.*
    name: 'NO empty description'
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with either **what** was changed, **why** it was changed, or **how** it was changed.
  - when: schedule.repository
    name: 'Check stale PR and issues'
    validate:
      - do: stale
        days: 20
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
  - when: pull_request.opened
    name: 'Greet a contributor'
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Thanks for creating a pull request! A maintainer will review your changes shortly. Please don't be discouraged if it takes a while.
  - when: pull_request.*, pull_request_review.*
    name: 'Draft check'
    validate:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    fail:
      - do: comment
        payload:
          body: This PR is STILL a draft!
